override KERNELDIR := /home/dangku/mydroid/bananaPi/m2/source/android/BPI-M2-Android4.4/lichee/linux-3.3
override KERNEL_COMPONENTS := srvkm dc_sunxi
override KERNEL_CROSS_COMPILE := arm-linux-gnueabi-
override PVR_SYSTEM := sunxi
override BUILD := release
override DEBUGLINK := 1
override OPTIM := -O2
override SUPPORT_ION := 1
override SUPPORT_PVRSRV_DEVICE_CLASS := 1
override PVR_ANDROID_NATIVE_WINDOW_HAS_SYNC := 1
